services:
  cp-proxy:
    container_name: proxy
    restart: always
    build: 
      context: ./proxy
    ports:
      - 80:80
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"    # Collector, OpenTelemetry gRPC
      - "4318:4318"    # Collector, OpenTelemetry gRPC
    environment:
      # This tells Jaeger that it should run the UI with a given prefix.
      QUERY_BASE_PATH: /jaeger
